apiVersion: apps/v1
kind: Deployment
metadata:
  name: whalesay-deployment
spec:
  selector:
    matchLabels:
      app: whalesay
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: whalesay
    spec:
      containers:
        - name: whalesay
          image: docker/whalesay:latest
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args: ["cowsay hello; sleep infinity"]
